apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: flinkoperatordeployment
  namespace: default
spec:
  #dependencies:
  api:
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: flinkoperatordeployment.example.promise.syntasso.io
  spec:
    group: example.promise.syntasso.io
    scope: Namespaced
    names:
      plural: flinkoperatordeployments
      singular: flinkoperatordeployment
      kind: FlinkOperatorDeployment
    versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name:
                    type: string
  #workflows:
