#!/bin/sh

set -eux

if [ $KRATIX_WORKFLOW_TYPE == "promise" ]; then
  cp /tmp/transfer/dependencies/* /kratix/output/
else
  base_instance="/tmp/transfer/resources/minimal-postgres-manifest.yaml"

  # Read current values from the provided resource request
  name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
  namespace="$(yq eval '.spec.namespace // "default"' /kratix/input/object.yaml)"


#Get the name from the Promise Custom resource
instanceName=$(yq eval '.spec.name' /kratix/input/object.yaml)

# Inject the name into the Jenkins resources
find /tmp/transfer -type f -exec sed -i \
  -e "s/<tbr-name>/${instanceName}/g" \
  {} \;

cp /tmp/transfer/* /kratix/output/