---
name: Entrypoint

on:
  # IMPORTANT: workflow_dispatch needs to be entered before other properties
  workflow_dispatch:

  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "rustlang"

permissions:
  actions: read
  checks: write
  contents: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  security-events: write
  id-token: write

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/linter.yml
    secrets: inherit
  build:
    name: Docker
    needs: linter
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
