---
name: Entrypoint

on:
  # IMPORTANT: workflow_dispatch needs to be entered before other properties
  workflow_dispatch:

  pull_request:
    branches:
      - "main"

permissions:
  actions: read
  checks: write
  contents: write
  issues: read
  packages: write
  pull-requests: write
  statuses: read
  security-events: write
  id-token: write

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/lint.yml
    permissions:
      deployments: read
      discussions: read
      pages: read
      repository-projects: read
    secrets: inherit
  build:
    name: Docker
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
